//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int productID { get; set; }
        public string fabricInfo { get; set; }
        public string productName { get; set; }
        public string garmentDes { get; set; }
        public string fontName { get; set; }
        public string fontNumber { get; set; }
        public string garmentImg { get; set; }
        public string garmentSpecf { get; set; }
        public Nullable<int> chestXs { get; set; }
        public Nullable<int> chestS { get; set; }
        public Nullable<int> chestM { get; set; }
        public Nullable<int> chestL { get; set; }
        public Nullable<int> chestXl { get; set; }
        public Nullable<int> chest2xl { get; set; }
        public Nullable<int> chest3xl { get; set; }
        public Nullable<int> chest4xl { get; set; }
        public Nullable<int> chest5xl { get; set; }
        public Nullable<int> lengthXs { get; set; }
        public Nullable<int> lengthS { get; set; }
        public Nullable<int> lengthM { get; set; }
        public Nullable<int> lengthL { get; set; }
        public Nullable<int> lengthXl { get; set; }
        public Nullable<int> length2xl { get; set; }
        public Nullable<int> length3xl { get; set; }
        public Nullable<int> length4xl { get; set; }
        public Nullable<int> length5xl { get; set; }
        public string specialInstruction { get; set; }
        public string signature { get; set; }
        public string orderedDate { get; set; }
        public string requiredDate { get; set; }
        public string favcolor1 { get; set; }
        public string favcolorText1 { get; set; }
        public string favcolor2 { get; set; }
        public string favcolorText2 { get; set; }
        public string favcolor3 { get; set; }
        public string favcolorText3 { get; set; }
        public string favcolor4 { get; set; }
        public string favcolorText4 { get; set; }
        public string favcolor5 { get; set; }
        public string favcolorText5 { get; set; }
        public string favcolor6 { get; set; }
        public string favcolorText6 { get; set; }
        public string piecesXs { get; set; }
        public string piecesS { get; set; }
        public string piecesM { get; set; }
        public string piecesL { get; set; }
        public string piecesXl { get; set; }
        public string pieces2xl { get; set; }
        public string pieces3xl { get; set; }
        public string pieces4xl { get; set; }
        public string pieces5xl { get; set; }
        public string pieces6xl { get; set; }
        public string pieces7xl { get; set; }
        public string piecesTotal { get; set; }
        public string labelText1 { get; set; }
        public string labelImg1 { get; set; }
        public string labelText2 { get; set; }
        public string labelImg2 { get; set; }
        public string logoText1 { get; set; }
        public string logoText2 { get; set; }
        public string logoText3 { get; set; }
        public string logoText4 { get; set; }
        public string logoImg1 { get; set; }
        public string logoImg2 { get; set; }
        public string logoImg3 { get; set; }
        public string logoImg4 { get; set; }
    }
}
